RANDOMWALK-20: Init service and add club service Graphql API
ru-random-walk/club-service pull request #1
Opened 2024-12-20 22:30 UTC by maksmolchdmitr

2024-12-21 07:17 UTC, kryakobess commented on src/main/resources/graphql/club-service-api.graphqls
> +type Club {
Тут кодогенерация происходит или это пока просто описание?

2024-12-21 10:18 UTC, maksmolchdmitr commented on src/main/resources/graphql/club-service-api.graphqls
> +type Club {
Описание моделек, запросов и входных данных  с мутациями

2024-12-28 13:17 UTC, kryakobess requested changes

2024-12-28 13:17 UTC, kryakobess commented on src/main/java/ru/random/walk/club_service/controller/TestController.java
> +public class TestController {
Мне не нравится что так много слова тест везде, я начинаю путаться, сначала думал, что это просто тестовый код или код для теста, но оказалось, что это относится к домену, может поменяем имя этой сущности на Form (форма, анкета)?

2024-12-28 13:17 UTC, kryakobess commented on src/main/java/ru/random/walk/club_service/model/domain/answer/FormAnswerData.java
> +public class FormAnswerData extends AnswerData {
_**Рекомендация:**_ Можешь использовать @Value ломбока, если хочешь, чтобы класс был как record

2024-12-28 13:17 UTC, kryakobess commented on src/main/java/ru/random/walk/club_service/model/entity/AnswerEntity.java
> +    private TestEntity test;
А почему 1-1? разве у одного теста не может быть много вопросов и ответов?

2024-12-28 13:17 UTC, kryakobess commented on src/main/java/ru/random/walk/club_service/util/StubDataUtil.java
> +public class StubDataUtil {
что это и зачем? Может аннотацию добавить/deprecated пометить, если надо будет удалять?

2024-12-28 13:51 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/controller/TestController.java
> +public class TestController {
Дааа, тоже так хотел сделать

2024-12-28 13:52 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/controller/TestController.java
> +public class TestController {
Только Form уже есть

2024-12-28 13:56 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/controller/TestController.java
> +public class TestController {
Нее, ты не понял домен, это не форма или анкета, это именно тест для групп 
![image](https://github.com/user-attachments/assets/c14b6350-5d47-434a-8998-138a85514e6a)
А в свою очередь тест может быть либо подтверждением участников либо формой
![image](https://github.com/user-attachments/assets/5876232f-2d5e-4120-b9c0-3832de75cc63)

2024-12-28 14:07 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/model/entity/AnswerEntity.java
> +    private TestEntity test;
Нет

2025-01-03 14:01 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/model/domain/answer/FormAnswerData.java
> +public class FormAnswerData extends AnswerData {
Нельзя, там для Jakson нужен дефолтный конструктор:
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `ru.random.walk.club_service.model.domain.answer.FormAnswerData` (no Creators, like default constructor, exist)`
А @Value только для иммутабельных классов, а мне собсна мутабильные нужны

2025-01-03 14:02 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/club_service/util/StubDataUtil.java
> +public class StubDataUtil {
Добавил тесты конвертеров - там это нужно и также в других ситуациях для тестирования можно использовать

2025-01-03 14:13 UTC, kryakobess commented on src/main/java/ru/random/walk/club_service/util/StubDataUtil.java
> +public class StubDataUtil {
Так почему если это для тестов, оно находится в main каталоге?

2025-01-03 14:22 UTC, kryakobess approved these changes

2025-01-03 14:23 UTC, merged