RANDOMWALK-87-add-CI-CD-pipeline
ru-random-walk/club-service pull request #3
Opened 2024-12-29 11:36 UTC by maksmolchdmitr

2025-01-04 07:38 UTC, kryakobess requested changes

2025-01-04 07:38 UTC, kryakobess commented on deploy/club-service/values.yaml
> +    value: "INFO"
Зачем это надо?

2025-01-04 07:38 UTC, kryakobess commented on deploy/club-service/values.yaml
> +    value: "false"
Если фолс, то зачем вообще добавлять

2025-01-04 08:40 UTC, kryakobess requested changes

2025-01-04 08:40 UTC, kryakobess commented on .github/workflows/workflow.yaml
> +      name: approvers
Задай environment в настройках репозитория, approvers должны быть ты и я

2025-01-04 13:02 UTC, maksmolchdmitr commented on deploy/club-service/values.yaml
> +    value: "INFO"
Чтобы быстро если нужно проставлять env vars для просмотра логов jpa

2025-01-04 13:02 UTC, maksmolchdmitr commented on deploy/club-service/values.yaml
> +    value: "false"
Чтобы быстро если нужно проставлять env vars для просмотра логов jpa

2025-02-06 17:55 UTC, kryakobess approved these changes

2025-02-08 07:29 UTC, kryakobess approved these changes

2025-02-08 07:30 UTC, merged